trigger:
  - none
pr:
  - none

# developer_token is temproraly 


variables:
  - name: vmImageName
    value: 'windows-latest'

jobs:
  - job: 
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $foo = Get-Content '.\botium.json' | Out-String | ConvertFrom-Json
            $myJson = Get-Content .\botium.json -Raw | ConvertFrom-Json

            $foo.botium.Capabilities.SIMPLEREST_HEADERS_TEMPLATE.Authorization=$foo.botium.Capabilities.SIMPLEREST_HEADERS_TEMPLATE.Authorization.replace('##endpointKey##','hi')
            Write-Host $foo.botium.Capabilities.SIMPLEREST_HEADERS_TEMPLATE.Authorization
            
    