trigger:
  - none
pr:
  - none

# developer_token is temproraly 

jobs:
  - job: 
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $foo = [FooObject](Get-Content 'botium.json' | Out-String | ConvertFrom-Json)
            
            Write-Host $foo
    