trigger:
- none

pr:
- none

# developer_token is temproraly 
parameters:  
- name: developer_token
  displayName: developer token from box app
  type: string

variables:
  - group: 'training-center'
  - name: vmImageName
    value: 'windows-latest'

jobs:
  - job:
    displayName: Sync Analytics
    pool:
      vmImage: $(vmImageName)
    steps:
      - template: python-template.yml
        parameters:
          execute_path: ANALYTIC
          developer_token: ${{ parameters.developer_token }}
          feedback_files: '' 