trigger:
- none

pr:
- none

parameters:
- name: execute_path
  displayName: chose part to execute
  values:
  - 'ANALYTIC'
  - 'NOTIFICATION'

- name: developer_token
  displayName: developer token from box app
  type: string

variables:
  - group: 'training-center'
  - name: vmImageName
    value: 'windows-latest'


jobs:
  - job:
    displayName: Prepare Notification
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: PowerShell@2
        inputs:
          targetType: inline
          script: |
            python -m venv venv
            pip3 install -r requirements.txt
        displayName: Install Dependencies
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            Write-Host ${{ parameters.execute_path }}
            python -m venv venv
            cd src
            
            $env:BOX_CLIENT_ID = "$(non-prod-box-client-id)"
            $env:BOX_CLIENT_SECRET = "$(non-prod-box-client-secret)"
            $env:BOX_DEVELOPER_TOKEN = "${{ parameters.developer_token }}"
            $env:BOX_FOLDER_ID = "$(non-prod-box-folder-id)"
            $env:AZURE_APPLICATION_INSIGHTS_KEY = "$(non-prod-app-ins-key)"
            $env:AZURE_APPLICATION_INSIGHTS_ID = "$(non-prod-app-ins-id)"
            $env:AZURE_APPLICATION_INSIGHTS_BASE_URL = "$(non-prod-app-ins-url)"
            $env:LOCAL_FILE_PATH = "../data/" 
            $env:TEMPLATE_FILE_PATH= "../data/templates/"
            
            python app.py --execute=${{ parameters.execute_path }}
        displayName: 'Proccess Analytics'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '../data/notifications'
          Contents: '**'
          TargetFolder: '$(Pipeline.Workspace)'
          
      - publish: '$(Pipeline.Workspace)'
        displayName: 'publish notification_list'
        artifact: drop

