trigger:
- none

pr:
- none

parameters:
- name: developer_token
  displayName: developer token from box app
  type: string

variables:
  - group: 'training-center'
  - name: vmImageName
    value: 'windows-latest'
  - name: json_data
    value: empty

jobs:
  - job: prepare_notification
    displayName: Prepare Notification
    pool:
      vmImage: $(vmImageName)
    steps:
      - template: python-template.yml
        parameters:
          execute_path: NOTIFICATION
          developer_token: ${{ parameters.developer_token }}
          feedback_files: ' '
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'data/notifications'
          Contents: '**.xlsx'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            $message = "message from prepare notification job"
            Write-Host "##vso[task.setvariable variable=new_test_value;isOutput=true;] $message"
            Write-Host '$(Build.ArtifactStagingDirectory)'
            
      - publish: '$(Build.ArtifactStagingDirectory)'
        displayName: 'publish notification_list'
        artifact: drop
  - job: send_notification
    displayName: Send Notification
    pool:
      vmImage: $(vmImageName)          
    dependsOn: prepare_notification
    variables: 
      someName: $[ dependencies.prepare_notification.outputs['setVariable.new_test_value'] ]
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            
            # Write your PowerShell commands here.
            Write-Host passed $(someName)
            Write-Host '$(Build.ArtifactStagingDirectory)'
  - job:
    displayName: Finalize Notification
    pool:
      vmImage: $(vmImageName)
    dependsOn: send_notification
    variables: 
      someName: $[ dependencies.prepare_notification.outputs['setVariable.new_test_value'] ]
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $value_here = $(someName)
            # Write your PowerShell commands here.
            
            Write-Host new test value $value_here
            Write-Host '$(Build.ArtifactStagingDirectory)'
      - template: python-template.yml
        parameters:
          execute_path: CUSTOM
          feedback_files: $(json_data)
          developer_token: ${{ parameters.developer_token }}