trigger:
- none

pr:
- none

# developer_token is temproraly 
parameters:  
- name: developer_token
  displayName: developer token from box app
  type: string
- name: send
  type: number


variables:
  - group: 'training-center'
  - name: vmImageName
    value: 'windows-latest'

jobs:
  - job: preparation
    pool:
      vmInage: $(vmImageName)
    steps:
      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'Box APP.txt'
      - task: CopyFiles@2
        inputs:
            SourceFolder: '$(Agent.TempDirectory)'
            Contents: 'Box APP.txt'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - publish: '$(Build.ArtifactStagingDirectory)'
        displayName: 'publish notification_list'
        artifact: drop

  - job:
    dependsOn: preparation

    displayName: Sync Analytics
    pool:
      vmImage: $(vmImageName)
    steps:

      - template: python-template.yml
        parameters:
          execute_path: ANALYTIC
          developer_token: ${{ parameters.developer_token }}
          feedback_files: '' 