trigger:
- none

pr:
- none

parameters:
- name: developer_token
  displayName: developer token from box app
  type: string

variables:
  - group: 'training-center'
  - name: vmImageName
    value: 'windows-latest'
  - name: json_data
    value: 'empty'
  - name: messageToSend
    value: 'default message to send'

jobs:
  - job: prepare_notification
    displayName: Prepare Notification
    pool:
      vmImage: $(vmImageName)
    steps:
      - template: python-template.yml
        parameters:
          execute_path: NOTIFICATION
          developer_token: ${{ parameters.developer_token }}
          feedback_files: ''
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'data/notifications'
          Contents: '**.xlsx'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            $message = "message from prepare notification job"
            Write-Host "##vso[task.setvariable variable=messageToSend;isOutput=true] $message"
            Write-Host "##vso[task.setvariable variable=json_data;isOutput=true] $(json_data)"
            Write-Host '$(Build.ArtifactStagingDirectory)'
        name: outputVars 
      - publish: '$(Build.ArtifactStagingDirectory)'
        displayName: 'publish notification_list'
        artifact: drop  

  - job: send_notification
    displayName: Send Notification
    pool:
      vmImage: $(vmImageName)          
    dependsOn: prepare_notification
    variables:
      localVariable: $[dependencies.prepare_notification.outputs['outputVars.messageToSend']]
      feedback: $[dependencies.prepare_notification.outputs['outputVars.json_data']]
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            $messageHere = "$(localVariable)"
            $feedback_data = "$(feedback)"
            Write-Host "##vso[task.setvariable variable=messageToSend;isOutput=true] $messageHere"
            Write-Host "##vso[task.setvariable variable=json_data;isOutput=true] $feedback_data"
            Write-Host passed $messageHere
            Write-Host '$(Build.ArtifactStagingDirectory)'
        name: outputVars
  - job:
    displayName: Finalize Notification
    pool:
      vmImage: $(vmImageName)
    dependsOn: send_notification
    variables:
      feedback: $[dependencies.send_notification.outputs['outputVars.json_data']]
      localVariable: $[dependencies.send_notification.outputs['outputVars.messageToSend']]
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            $messageHere = "$(localVariable)"
            $feedback = "$(feedback)"
            Write-Host feedback pased $feedback
            Write-Host passed $messageHere
            Write-Host '$(Build.ArtifactStagingDirectory)'
      - template: python-template.yml
        parameters:
          execute_path: CUSTOM
          developer_token: ${{ parameters.developer_token }}
          feedback_files: "$(feedback)"