trigger:
- none

pr:
- none

parameters:
- name: developer_token
  displayName: developer token from box app
  type: string

variables:
  - group: 'training-center'
  - name: vmImageName
    value: 'windows-latest'
  - name: json_data
    value: empty


jobs:
  - job: prepare_notification
    displayName: Prepare Notification
    pool:
      vmImage: $(vmImageName)
    steps:
      - template: python-template.yml
        parameters:
          execute_path: NOTIFICATION
          developer_token: ${{ parameters.developer_token }}
          feedback_files: ' '
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'data/notifications'
          Contents: '**.xlsx'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host '$(Build.ArtifactStagingDirectory)'
            
      - publish: '$(Build.ArtifactStagingDirectory)'
        displayName: 'publish notification_list'
        artifact: drop
  - job: send_notification
    displayName: Send Notification
    pool:
      vmImage: $(vmImageName)          
    dependsOn: prepare_notification
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.

            Write-Host '$(Build.ArtifactStagingDirectory)'
  - job:
    displayName: Finalize Notification
    pool:
      vmImage: $(vmImageName)
    dependsOn: send_notification
    steps:
      - template: python-template.yml
        parameters:
          execute_path: CUSTOM
          feedback_files: $(json_data)
          developer_token: ${{ parameters.developer_token }}