trigger:
  - none
pr:
  - none

# developer_token is temproraly 

parameters:
  - name: execute_path
    displayName: chose path to execute
    default: SYNC_ANALYTIC
    type: string
    values:
      - SYNC_ANALYTIC
      - UPDATE_QNA_MAKER

variables:
  - group: 'training-center'
  - name: vmImageName
    value: 'ubuntu-latest'

jobs:
  - job: 
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $foo = [FooObject](Get-Content 'botium.json' | Out-String | ConvertFrom-Json)
            
            Write-Host $foo
    