trigger:
  - none
pr:
  - none

# developer_token is temproraly 


variables:
  - name: vmImageName
    value: 'windows-latest'

jobs:
  - job: start
    steps:
      - task: PowerShell@2
        inputs:
          targetType: inline
          script: |
            (Get-Content -Path .\botium.json) |
              ForEach-Object {$_ -Replace '##endpointKey##', 'Caution'} |
                Set-Content -Path .\botium.json
  
  - job: sec
    dependsOn: start
    steps:
      - task: PowerShell@2
       
        inputs:
          targetType: 'inline'
          script: |
            $foo = Get-Content '.\botium.json' | Out-String | ConvertFrom-Json
            $myJson = Get-Content .\botium.json -Raw | ConvertFrom-Json
            Write-Host $foo.botium.Capabilities.SIMPLEREST_HEADERS_TEMPLATE.Authorization before
            $foo.botium.Capabilities.SIMPLEREST_HEADERS_TEMPLATE.Authorization=$foo.botium.Capabilities.SIMPLEREST_HEADERS_TEMPLATE.Authorization.replace('##endpointKey##','hi')
            Write-Host $foo.botium.Capabilities.SIMPLEREST_HEADERS_TEMPLATE.Authorization
            
    