trigger:
- none

pr:
- none

# developer_token is temproraly 
parameters:
- name: developer_token
  displayName: developer token from box app
  type: string

variables:
  - group: 'training-center'
  - name: vmImageName
    value: 'windows-latest'

jobs:
  - job:
    displayName: Sync Analytics
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host "Hello World"
            pip3 install -r requirements.txt
        displayName: Install Dependencies
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            cd src

            $env:BOX_CLIENT_ID = "$(non-prod-box-client-id)"
            $BOX_CLIENT_SECRET = $(non-prod-box-client-secret)
            $BOX_DEVELOPER_TOKEN = ${{ parameters.developer_token }}
            $BOX_FOLDER_ID = $(non-prod-box-folder-id)
            $AZURE_APPLICATION_INSIGHTS_KEY = $(non-prod-app-ins-key)
            $AZURE_APPLICATION_INSIGHTS_ID = $(non-prod-app-ins-id)
            $AZURE_APPLICATION_INSIGHTS_BASE_URL = $(non-prod-app-ins-url)
            $LOCAL_FILE_PATH = "data/" 
            $TEMPLATE_FILE_PATH= "data/templates/"
            
            python app.py --execute=ANALYTIC            
        displayName: 'Proccess Analytics'  