trigger:
- none

pr:
- none

# developer_token is temproraly 
parameters:
- name: developer_token
  displayName: developer token from box app
  type: string

variables:
  - group: 'training-center'
  - name: vmImageName
    value: 'windows-latest'

jobs:
  - job:
    displayName: Sync Analytics
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            python -m venv venv
            Write-Host "Hello World"
            pip3 install -r requirements.txt
        displayName: Install Dependencies
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            python -m venv venv
            cd src
            
            $env:BOX_CLIENT_ID = "$(non-prod-box-client-id)"
            $env:BOX_CLIENT_SECRET = "$(non-prod-box-client-secret)"
            $env:BOX_DEVELOPER_TOKEN = "${{ parameters.developer_token }}"
            $env:BOX_FOLDER_ID = "$(non-prod-box-folder-id)"
            $env:AZURE_APPLICATION_INSIGHTS_KEY = "$(non-prod-app-ins-key)"
            $env:AZURE_APPLICATION_INSIGHTS_ID = "$(non-prod-app-ins-id)"
            $env:AZURE_APPLICATION_INSIGHTS_BASE_URL = "$(non-prod-app-ins-url)"
            $env:LOCAL_FILE_PATH = "../data/" 
            $env:TEMPLATE_FILE_PATH= "../data/templates/"
            
            python app.py --execute=ANALYTIC            
        displayName: 'Proccess Analytics'  