trigger:
  - none
pr:
  - none

# developer_token is temproraly 


variables:
  - name: vmImageName
    value: 'windows-latest'

jobs:
  - job: 
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            $foo = Get-Content 'botium.json' | Out-String | ConvertFrom-Json
            
            Write-Host $foo
    