trigger:
- none

pr:
- none


variables:
  - name: vmImageName
    value: 'windows-latest'
  - name: json_data
    value: 'empty'

resources:
  repositories:
    - repository: QnARepository
      type: github
      endpoint: zulu1990
      name: zulu1990/QnA-Repo
      ref: refs/heads/main

jobs:
  - job: send_notification
    displayName: Send Notification
    pool:
      vmImage: $(vmImageName)
    variables:
      checkoutPath: 's/qna-repo'
    steps:
    - checkout: QnARepository
      displayName: Checkout QnA Repository
      path: $(checkoutPath)
      persistCredentials: true  
      clean: true
    - script: |
        git config --global user.email archili_zivzivadze@epam.com & git config --global user.name "Pipeline"
        git checkout -b "feat/$(Build.BuildNumber)"
        git pull

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $FolderName = Join-Path -Path $(checkoutPath) -ChildPath "kb-at/Test"
          $FileName = $FolderName + '/TestFile.txt'
          if (Test-Path $FolderName) {
   
              Write-Host "Folder Exists"
              # Perform Delete file from folder operation
          }
          else
          {
  
              #PowerShell Create directory if not exists
              New-Item $FolderName -ItemType Directory
              Write-Host "Folder Created successfully"
          }

          if (!(Test-Path $FileName))
          {
            New-Item -path $FolderName -name TestFile.txt -type "file" -value "my new text"
            Write-Host "Created new file and text content added"
          }
          else
          {
            Add-Content -path $FileName -value "new text content"
            Write-Host "File already exists and new text content added"
          }

    - script: |
        git status
        git add .
        git commit -m "deployment $(Build.BuildNumber)"
        git status
        git push --set-upstream
      displayName: Add data.txt file
      #workingDirectory: $(checkoutPath)