trigger:
- none

pr:
- none

parameters:
- name: execute_path
  displayName: chose part to execute
  values:
  - 'ANALYTIC'
  - 'NOTIFICATION'

- name: developer_token
  displayName: developer token from box app
  type: string

variables:
  - group: 'training-center'
  - name: vmImageName
    value: 'windows-latest'


jobs:
  - job: prepare_notification
    displayName: Prepare Notification
    pool:
      vmImage: $(vmImageName)
    steps:
      - template: azure-pipeline.yml
        parameters:
          execute_path: ${{ parameters.execute_path }}
          developer_token: ${{ parameters.developer_token }}
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'data/notifications'
          Contents: '**.xlsx'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            
            Write-Host '$(Build.ArtifactStagingDirectory)'
            
      - publish: '$(Build.ArtifactStagingDirectory)'
        displayName: 'publish notification_list'
        artifact: drop